apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nitishmedhi/my-analytics:${{ github.sha }}
        ports:
        - containerPort: 80
