name: Deploy to Kubernetes Self-hosted-Runner(Docker Desktop)

on:
  workflow_dispatch: # Trigger manually via GitHub UI or with specific events if required

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List files in the current directory
        run: ls -la
        
      - name: Set up Kubernetes context
        run: |
          kubectl config use-context docker-desktop

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Image
        run: docker pull nitishmedhi/my-analytics:latest

      - name: Apply Kubernetes Deployment
        run: |
          kubectl set image deployment/nginx-deployment nginx=nitishmedhi/my-analytics:latest -n my-analytics
          kubectl apply -f k8s/nginx-deployment.yaml -n my-analytics
